#spring:
#  datasource:
#      username: root
#      password: Dssql1211!#*
#      url: jdbc:mysql://192.168.0.119:3306/ds?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8088
spring:
  datasource:
    username: root
    password: Dssql1211!#*
    url: jdbc:mysql://192.168.0.119:3306/ds?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver


