package com.zongze.security.component.entity;

import java.util.Date;

public class ManagerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.manager_no
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String managerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.org_id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.phone
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.uname
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.pwd
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.role_name
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.belong_sys
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String belongSys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.state
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.comments
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.create_date
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_user.is_liable
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    private Integer isLiable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.id
     *
     * @return the value of manager_user.id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.id
     *
     * @param id the value for manager_user.id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.manager_no
     *
     * @return the value of manager_user.manager_no
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getManagerNo() {
        return managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.manager_no
     *
     * @param managerNo the value for manager_user.manager_no
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setManagerNo(String managerNo) {
        this.managerNo = managerNo == null ? null : managerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.org_id
     *
     * @return the value of manager_user.org_id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.org_id
     *
     * @param orgId the value for manager_user.org_id
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.phone
     *
     * @return the value of manager_user.phone
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.phone
     *
     * @param phone the value for manager_user.phone
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.uname
     *
     * @return the value of manager_user.uname
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.uname
     *
     * @param uname the value for manager_user.uname
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.pwd
     *
     * @return the value of manager_user.pwd
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.pwd
     *
     * @param pwd the value for manager_user.pwd
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.role_name
     *
     * @return the value of manager_user.role_name
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.role_name
     *
     * @param roleName the value for manager_user.role_name
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.belong_sys
     *
     * @return the value of manager_user.belong_sys
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getBelongSys() {
        return belongSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.belong_sys
     *
     * @param belongSys the value for manager_user.belong_sys
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setBelongSys(String belongSys) {
        this.belongSys = belongSys == null ? null : belongSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.state
     *
     * @return the value of manager_user.state
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.state
     *
     * @param state the value for manager_user.state
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.comments
     *
     * @return the value of manager_user.comments
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.comments
     *
     * @param comments the value for manager_user.comments
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.create_date
     *
     * @return the value of manager_user.create_date
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.create_date
     *
     * @param createDate the value for manager_user.create_date
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_user.is_liable
     *
     * @return the value of manager_user.is_liable
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public Integer getIsLiable() {
        return isLiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_user.is_liable
     *
     * @param isLiable the value for manager_user.is_liable
     *
     * @mbggenerated Mon Nov 26 15:43:55 CST 2018
     */
    public void setIsLiable(Integer isLiable) {
        this.isLiable = isLiable;
    }
}